FROM node:18-bullseye-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl libssl-dev && rm -rf /var/lib/apt/lists/*

COPY backend/package*.json ./
RUN npm install

COPY backend/ .

RUN npx prisma generate --schema=src/prisma/schema.prisma
RUN npm run build

EXPOSE 3001

CMD ["node", "dist/index.js"]
