FROM node:20-slim
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY backend/package*.json ./
RUN npm install

COPY backend/ .

RUN npx prisma generate --schema=src/prisma/schema.prisma
RUN npm run build

EXPOSE 3001

CMD ["sh", "-c", "npx prisma db push --schema=src/prisma/schema.prisma && node dist/index.js"]
